version: '3.4'

services:
  mmkennels:
    image: ${DOCKER_REGISTRY-}mmkennels
    build:
      context: .
      dockerfile: MM Kennels/Dockerfile
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      SA_PASSWORD: UZPDju5w9RF6juprfwu1
      ACCEPT_EULA: Y
    volumes:
      - "sqlvolume:/var/opt/mssql"

volumes:
  sqlvolume:
